Add an option for photo refresh rate & a simple clock
jenil/huntsplash pull request #1
Opened 2017-06-08 23:23 UTC by ZachNagengast

Hi! Found this repo while googling, though it was cool so added a few more features. Take a look and let me know what you think.

2017-06-09 05:25 UTC, jenil commented
Hey @ZachNagengast 

Great work 👍 

Everything looks good, just that can we move the clock position to the bottom-center of the page and also reduce the size to about 50%? I want the center of the photo to get some visibility.

2017-06-09 05:28 UTC, ZachNagengast commented
Sure! I'm also updating the logic a bit so that it loads faster when a new image is ready to load in. I'll have a few more updates soon.

2017-06-09 05:30 UTC, ZachNagengast commented
There also might be an issue with unsplash api rate limits with the custom refresh interval option, I'm looking into that as well.

2017-06-09 05:32 UTC, jenil commented
I don't think the Unsplash API rate limit should be a problem, we have 5k rq/hr and we can request for more if needed.

2017-06-09 05:33 UTC, ZachNagengast commented
Cool, perhaps you can look at your usage and recommend a minimum refresh rate, I'm testing with refreshing the image every new tab and it goes quick.

2017-06-09 05:35 UTC, jenil commented
Here:
![image](https://user-images.githubusercontent.com/971411/26962397-848cf45c-4d03-11e7-8977-7c5001ee5d47.png)

It hardly goes over 6 request right now

2017-06-09 08:03 UTC, ZachNagengast commented
Added image preloading, works nicely on my machine. Updated the clock too, looks better. I was getting some errors with the caching portion, maybe you can take a look, but it seems to still work. It loads and caches an extra image every time the current one updates, so it's always ahead by 1 and the user shouldn't see any loading. Normally this kind of thing should probably be done with a background.js script (I noticed http://instant.unsplash.com/ does this), but this method seems to work well enough. Open to any thoughts you had.

2017-06-09 12:26 UTC, jenil commented on src/components/bg.vue
> +        this.$http.get(cacheBG).then(response => {
Can you change this line to `this.$http.get(cacheBG, { responseType: 'blob' }).then(response => {`?
This will solve the error of caching the image.

2017-06-14 08:04 UTC, ZachNagengast commented on src/components/bg.vue
> +        this.$http.get(cacheBG).then(response => {
This worked, thanks!

2017-06-14 08:05 UTC, ZachNagengast commented
Updated that issue with tracking, also added a greeting that changes based on the time of day.

2017-06-14 11:50 UTC, jenil requested changes
Hey @ZachNagengast, just review the changes and they work beautifully! I have left a few comments (minor CSS changes), once those are fixed I'll merge the PR :)

2017-06-14 11:50 UTC, jenil commented on src/components/clock.vue
> +.center {
Can you update the CSS here to?
```
    position: fixed;
    bottom: 0.5rem;
    left: 50%;
    -webkit-transform: translate(-50%, 0%);
```

2017-06-14 11:50 UTC, jenil commented on src/components/clock.vue
> +  font-size: 5rem;
add `line-height: 1;`

2017-06-14 11:50 UTC, jenil commented on src/components/clock.vue
> +  font-size: 3rem;
change font-size to 1.5rem

2017-06-16 07:38 UTC, ZachNagengast commented
Cool, added!

2017-06-16 13:05 UTC, jenil approved these changes

2017-06-16 13:06 UTC, merged

2017-06-16 13:53 UTC, jenil commented
🥇 Awesome! Thank you :) 
Publishing 1.0.0 now... 🥂